### ISSUE TITLE
Won't run on Amazon EC2 Windows 2012

### ISSUE THREAD

**Issue by davehodg** [dnmfarrell/berrybrew#18]
Grumbles about not being 64-bit. Worked fine on my local PC.

Any ideas? Feel free to close immediately if it's a silly Windows question!

**Comment by stevieb9** [comment]
I'll investigate this. With permission of David, I'll be merging my forked version https://github.com/stevieb9/berrybrew into this repository as the former has had a lot of features added.

I'll take this issue into consideration, as I do most of my testing in my EC2 instances anyhow.

Leaving open until after the merge, and I'll update to get you to test.

**Comment by stevieb9** [comment]
Closing. This is/was a known problem with AWS.
