### ISSUE TITLE
Error installing 5.30.0_64

### ISSUE THREAD

**Issue by sigzero** [dnmfarrell/berrybrew#22]
PS C:\WINDOWS\system32> berrybrew.exe install 5.30.0_64
Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-64bit-portable.zip to C:\berrybrew\temp\strawberry-perl-5.30.0.1-64bit-portable.zip
Confirming checksum ...
Checksum OK

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The system cannot find the file specified.
   at BerryBrew.Berrybrew.Extract(StrawberryPerl perl, String archivePath)
   at BerryBrew.Berrybrew.Install(String version)
   at berrybrew.Bbconsole.Main(String[] args)

**Comment by stevieb9** [comment]
Thanks for the report. I'll have a look into this shortly.

**Comment by stevieb9** [comment]
Could you please let me know where your `berrybrew` is installed to, and include the output of `echo %PATH` is?

**Comment by sigzero** [comment]
I have berrybrew installed at C:\Users\rlhicks\berrybrew

PATH=C:\jdk1.7.0_80\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\HID Global\ActivClient\;C:\Program Files\HID Global\ActivClient\;C:\jre1.7.0_80\bin;C:\Apps\curl\bin;C:\brew\bin;C:\Users\rlhicks\berrybrew\bin;C:\Users\rlhicks\AppData\Local\Microsoft\WindowsApps;C:\Bin;C:\JavaTools\AStyle\bin;C:\pandoc;C:\Users\rlhicks\AppData\Local\Programs\Microsoft VS Code\bin;C:\Vim\vim81;C:\apache-maven-3.6.1\bin;C:\apache-ant-1.10.5\bin;C:\Program Files\Bandizip\;

**Comment by stevieb9** [comment]
Great, thanks. Everything looks good there.

Could I ask one more thing, that you let me know which version you're on? ie. `berrybrew version`.

I was preparing for the next production release today, so I'd like to get this investigated fully before I do so.

**Comment by sigzero** [comment]
The version is 1.23

**Comment by sigzero** [comment]
Ah! I did not have that DLL anywhere. I downloaded the latest ICSharpCode.SharpZipLib.dll and put it in the berrybrew bin directory and everything worked.

**Comment by stevieb9** [comment]
Ok that's some great feedback. That dll should have been included in the distribution. I'll do my best to figure out what happened there.

**Comment by sigzero** [comment]
That dll is in the pre-built archive. Not sure why it disappeared. It must have been something I did.
