### ISSUE TITLE
Exec not working with cloned perls

### ISSUE THREAD

**Issue by TBSliver** [dnmfarrell/berrybrew#23]
Hey, having issues with exec with custom cloned perls, where exec is just not doing anything it seems. To reproduce:

```
$ berrybrew install 5.30.0_64
$ berrybrew clone 5.30.0_64_custom
$ berrybrew exec --with 5.30.0_64 perl -e "print qq{hello\n}"
hello
$ berrybrew exec --with 5.30.0_64_custom perl -e "print qq{hello\n}"
```

Dont know whats going on, but dont get an output from the custom perl at all, although doing berrybrew use on it does work.

Doesnt work when using as multiple --with arguments either:

```
$ berrybrew exec --with 5.30.0_64,5.30.0_64,5.30.0_64_custom perl -e 'print qq{hello\n}'
perl-5.30.0_64
==============
hello
perl-5.30.0_64
==============
hello
```

**Comment by stevieb9** [comment]
Thanks for the report. I'll investigate as soon as I can.

**Comment by stevieb9** [comment]
This is because we don't `exec` on custom Perl instances by default. In the `data/config.json` file, set `custom_exec` to `true` to change this behaviour.

I am currently working on this project, and I'll make this more clear in the documentation.

**Comment by stevieb9** [comment]
After changing `custom_exec` from` false` (the default) to `true` in the `data\config.json` file, it works as expected:

```
c:\repos\berrybrew>berrybrew clone 5.10.1_32 clone-test
Successfully registered clone-test
Successfully installed custom perl 'clone-test'

c:\repos\berrybrew>berrybrew exec perl -E "say 'hi'"

perl-5.10.1_32
==============
hi
perl-clone-test
==============
hi
```
