### ISSUE TITLE
How to open the UI?

### ISSUE THREAD

**Issue by hakonhagland** [dnmfarrell/berrybrew#24]
A simple question: I just tried to install `berrybrew` on Windows 10 using the executable `berrybrewInstaller.exe`. How do I open the UI after installation ? There is no icon in the system tray that I can click on. If I type `berry` in the search box in the task bar it just shows `berrybrewinstaller.exe`

**Comment by hakonhagland** [comment]
I think found it. I had to restart my machine, then I found the UI by click on the hat sign in the task bar:

![berry](https://user-images.githubusercontent.com/6708379/121135877-3e5c7280-c835-11eb-8587-26116b4a97d7.PNG)

**Comment by stevieb9** [comment]
Yes. In some cases, the icon is hidden away, on other startups of the
machine, it's unhidden.

On my Windows system that I develop the software on, I've got three
non-hidden taskbar icons, and which ones are shown appear to be random.

**Comment by Phroneris** [comment]
The berrybrew UI is great but this should be more accessible!

I think the installer should have an option to add "berrybrew UI" to start menu.
It would be better to have "berrybrew UI (as Administrator)" one too because `switch`-ing without permission causes error via either the UI or `bb switch` command.

**Comment by Phroneris** [comment]
It would also great if the UI issues a warning like "UI is already running. See task icon area for existing instance." when a user tries to start an extra instance without being aware of an existing one.
(I don't know of any situation where the UI should be run in multiple instances.)
