### ISSUE TITLE
$ENV{HOME} is overridden

### ISSUE THREAD

**Issue by garfieldnate** [dnmfarrell/berrybrew#5]
My dzil setup stopped working, and it turned out to be because Strawberry portable overrides the HOME environment variable, replacing it with HOMEDIR and HOMEPATH (I found this by looking at File::HomeDir::Windows and Portable::HomeDir). So my home was changed to C:\berrybrew\5.20.1_64\data and dzil could no longer find my config located in C:\Users\Nate.

This isn't really a bug, just an inconvenience of using a portable distribution like an installed distribution. My fix for this was to comment out most of the `apply` method in vendor\lib\Portable\HomeDir.pm, but it might be nice to have an install option like "don't override HOME" or something.

**Comment by dnmfarrell** [comment]
Thanks for raising this, let me look into it

**Comment by dnmfarrell** [comment]
What if berrybrew installed in the users $HOME dir instead of C:/? I don't have access to a Windows machine atm to check.
I *thought* I read somewhere that there couldn't be any spaces in the directory PATH to the Perl and C binaries, but I might be wrong. (Can you have a Windows username with a space in it?. Not sure :) )

**Comment by garfieldnate** [comment]
You can have a user name with a space, and I did for a long time. Lots of things off of CPAN broke, so I reported lots of bugs, but of course it was inconvenient. I don't know if Strawberry Perl will run well or not in a path with a space, but I don't know if it would be a good idea even then.

But if berrybrew installed into the user's $HOME, then the installed Perls would use $HOME/berrybrew/5.20.1_64/data as the home directory instead of $HOME.
