### ISSUE TITLE
difficult to restart failed downloads

### ISSUE THREAD

**Issue by garfieldnate** [dnmfarrell/berrybrew#7]
I had started a `berrybrew install ...` operation earlier, and I accidentally closed the CMD before it finished. Silly me. Now when I run the same command to try to install the same version of Perl as earlier, I get this:

    C:\dev\berrybrew-3-10-2015\bin>berrybrew.exe install 5.20.1_64
    Confirming checksum ...
    Error checksum of downloaded archive does not match expected output
    expected: 844e7c2d741bda915ece0688bf3a00ab12577460
         got: 62d5ee01d994685b0877b9cb75ce3c89c8f1b7cd

The checksum will of course be wrong because I didn't let the download finish. So now I need to restart the download somehow. I would simply delete the old download and call `berrybrew install ...` again, but there is no message about the location of the bad download.

**Comment by hraharahra** [comment]
It is fixed in the last commit. I am closing it as resolved. If you have more ideas or setbacks, please create new issue.

**Comment by garfieldnate** [comment]
Thanks!
