### ISSUE TITLE
Currently used perl version might be hidden after upgrade

### ISSUE THREAD

**Issue by akauste** [dnmfarrell/berrybrew#8]
If berrybrew is upgraded and the new version does not have currently used perl in the available list it is hidden from list. It would be nice if the list would include all installed perls although they wouldn't be available for download anymore. It should be possible to switch back to them as well.

**Comment by hraharahra** [comment]
I agree. Old version should be available at least for switches if not for automatic download and installation. This brings some complications. I have few ideas how to do it, without too much changing how berrybrew works. 
I think, it would be acceptable solution, if old **installed** pearls are scanned at run-time and added to "available" list until they are uninstalled from the system. This should be paired with the ability to reinstall it somehow if need arise. Manual download of the old Strawberry Perl versions seems most plausible at the moment. 
Certainly looking to implement it, as this can easily become a source of nasty surprise and irritation.
