### ISSUE TITLE
Feature request: Set file association to current perl version when using berrybrew config

### ISSUE THREAD

**Issue by alabamapaul** [dnmfarrell/berrybrew#9]
When using berrybrew config, in addition to adding the current perl to the path environment variable, set the file association to allow running scripts without prepending perl

You can manipulate the registry as shown in this [MSDN article](https://msdn.microsoft.com/en-us/library/cc144158%28VS.85%29.aspx) or [Stackoverflow article](http://stackoverflow.com/questions/1387769/create-registry-entry-to-associate-file-extension-with-application-in-c) to set file associations

**Comment by dnmfarrell** [comment]
Great suggestion!

**Comment by shawnlaffan** [comment]
It's a good idea, but should perhaps be optional to avoid overriding some other perl, e.g. ActiveState.

There's also the risk that a long-running process that call a perl script will get a different version from that expected.  I don't know the intricacies of the registry settings and running processes, though, so maybe that's not an issue.

**Comment by dnmfarrell** [comment]
That's a good point. We should get the the user confirmation
